[package]
name = "yomiage-desktop"
description = "Discordのメッセージを読み上げるデスクトップアプリ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "yomiage_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
anyhow.workspace = true
directories.workspace = true
keyring.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-opener = "2.5.4"
tauri-plugin-process = "2.3.1"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-updater = { version = "2.10.1", default-features = false, features = ["native-tls", "zip"] }
tempfile.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender = "0.2.5"
tracing-subscriber.workspace = true
yomiage-core = { path = "../../../crates/yomiage-core" }
yomiage-discord = { path = "../../../crates/yomiage-discord" }

[lints]
workspace = true
